### ISSUE TITLE
Access $txid inside lua script

### ISSUE THREAD

**Issue by Roycohen** [streadway/ngx_txid#7]
Hi There,

I'm trying to access the $txid variable inside Lua script and for some reason it doesn't exist.
Example:
guid = ngx.var.txid

It is crashing because no txid variable exist.

**Comment by GUI** [comment]
I've been able to access this variable in lua scripts by explicitly setting another nginx variable to the `$txid` value. I imagine there might be some way to expose the `$txid` variable directly via the Lua APIs, but this simple workaround seems to do the trick.

So in my nginx config file, I add:

``` nginx
set $request_id $txid;
```

And then in my lua scripts, I'm able to access it like:

``` lua
local request_id = ngx.var.request_id
```

**Comment by Roycohen** [comment]
Thanks!!! :)
